# run_ddg.py
# script to run rosetta's ddg_monomer application
# takes input from preminimzation scripts and files defining target mutations as input

import socket
import sys
import os
import subprocess
import time
import multiprocessing

# inputs
input_pdb_file = os.path.abspath(sys.argv[1])
cst_filename = os.path.abspath(sys.argv[2])
input_mut_list = os.path.abspath(sys.argv[3])
# processes to run simultaneously
processes = int(sys.argv[4])

# paramsfiles?
input_params_file = None

# make output directory
output_dir = os.path.join(os.getcwd(), 'ddg_monomer_out')
try:
    os.makedirs(output_dir)
except OSError:
    if os.path.isdir(output_dir):
        print 'ERROR: Output directory \'ddg_monomer_out\' already exists, rename or remove it and re-run this script.'
        raise

# rosetta config
rosetta_bindir = "/opt/rosetta/rosetta_current/source/bin"
platform_tag = "linuxgccrelease"
rosetta_db_dir = "/opt/rosetta/rosetta_current/database"
rosetta_appname = "ddg_monomer"

# ddg_monomer options
write_pdbs = True
iterations = 1
# can these both be set 'true'? !!UNTESTED!!
report_mean = True
report_min = False

# load resfile list
with open(input_mut_list, 'r') as resfile_list:
    resfiles = resfile_list.readlines()
resfiles = [i.strip() for i in resfiles]

# TODO: read in above settings from a file instead of hardcoding
def get_settings():
    pass

# rosetta documentation recomended settings/flags for ddg_monomer
"""
-in:file:s <pdbfile of the preminimized wildtype structure> # the PDB file of the structure on which point mutations should be made
-ddg::mut_file <mutfile> # the list of point mutations to consider in this run
-ddg:weight_file soft_rep_design # Use soft-repulsive weights for the initial sidechain optimization stage
-ddg:minimization_scorefunction <weights file> # optional -- the weights file to use, if not given, then "score12" will be used (score12 = standard.wts + score12.wts_patch)
-ddg::minimization_patch <weights patch file > # optional -- the weight-patch file to apply to the weight file; does not have to be given
-database /path/to/minirosetta_database #the full oath to the database is required
-fa_max_dis 9.0 # optional -- if not given, the default value of 9.0 Angstroms is used.
-ddg::iterations 50 # 50 is the recommended number of iterations
-ddg::dump_pdbs true # write out PDB files for the structures, one for the wildtype and one for the pointmutant for each iteration
-ignore_unrecognized_res # optional -- if there are residues in the input PDB file that Rosetta cannot recognize, ignore them instead of quitting with an error message
-ddg::local_opt_only false # recommended: local optimization restricts the sidechain optimization to only the 8 A neighborhood of the mutation (equivalent to row 13)
-ddg::min_cst true # use distance restraints (aka constraints) during the backbone minimization phase
-constraints::cst_file <cbeta-distance-constraint-file> # the set of constraints to use during minimization which should reflect distances in the original (non-pre-relaxed) structure
-ddg::suppress_checkpointing true # don't checkpoint LIZ DOES CHECKPOINTING WORK AT ALL?
-in::file::fullatom # read the input PDB file as a fullatom structure
-ddg::mean false # do not report the mean energy
-ddg::min true # report the minimum energy
-ddg::sc_min_only false # do not minimize only the backbone during the backbone minimization phase
-ddg::ramp_repulsive true # perform three rounds of minimization (and not just the default 1 round) where the weight on the repulsive term is increased from 10% to 33% to 100%
-mute all # optional -- silence all of the log-file / stdout output generated by this protocol
-unmute core.optimization.LineMinimizer # optional -- unsilence a particular tracer
-ddg::output_silent true # write output to a silent file
"""

# input should be absolute path to a resfile
def run_ddg_monomer(resfile):
    # time this job
    time1 = time.time()

    # generate rosetta command line args
    # required flags
    rosetta_cmd = [
    os.path.join(rosetta_bindir,'%s.default.%s' % (rosetta_appname, platform_tag)),
    '-in:file:s',input_pdb_file,
    '-resfile',resfile,
    '-in:file:fullatom',
    '-ignore_unrecognized_res',
    '-fa_max_dis','9.0',
    '-ddg::suppress_checkpointing','true',
    '-ddg:weight_file','soft_rep_design',
    '-ddg::iterations',str(iterations),
    '-ddg::local_opt_only','false',
    '-ddg::min_cst','true',
    '-constraints::cst_file',cst_filename,
    '-ddg::sc_min_only','false',
    '-ddg::ramp_repulsive','true',
    '-ddg::suppress_checkpointing', 'true',
    '-in:auto_setup_metals'
    ]
    # conditional flags
    # add paramsfile option if needed !!UNTESTED!!
    if input_params_file:
        rosetta_cmd.append('-extra_res_fa')
        rosetta_cmd.append(input_params_file)
    # write out pdbs?
    if write_pdbs:
        rosetta_cmd.append('-ddg::dump_pdbs')
        rosetta_cmd.append('true')
    else:
        rosetta_cmd.append('-ddg::dump_pdbs')
        rosetta_cmd.append('false')
    # report mean ddg score?
    if report_mean:
        rosetta_cmd.append('-ddg::mean')
        rosetta_cmd.append('true')
    else:
        rosetta_cmd.append('-ddg::mean')
        rosetta_cmd.append('false')
    # report min ddg score?
    if report_min:
        rosetta_cmd.append('-ddg::min')
        rosetta_cmd.append('true')
    else:
        rosetta_cmd.append('-ddg::min')
        rosetta_cmd.append('false')

    # make a directory for this mutation
    mutation_name = resfile.split('/')[-1].split('.')[0]
    job_dir = os.path.join(output_dir, mutation_name)
    os.makedirs(job_dir)

    # write some system info to the log
    os.chdir(job_dir)
    with open('ddg%s.log' % mutation_name, 'w') as logfile:
        logfile.write("Python: %s\n" % sys.version)
        logfile.write("Host: %s\n" % socket.gethostname())
        logfile.write(' '.join(rosetta_cmd))
        logfile.write('\n')

    # call rosetta and output to log
    with open('ddg%s.log' % mutation_name, 'a+') as logfile:
        process = subprocess.Popen(rosetta_cmd, \
                                   stdout=logfile, \
                                   stderr=subprocess.STDOUT, \
                                   close_fds = True)
        returncode = process.wait()

    # write timing info to log
    time2 = time.time()
    runtime = time2 - time1
    with open('ddg%s.log' % mutation_name, 'a+') as logfile:
        logfile.write('\nruntime in sec: %s ' % str(runtime))

# for testing multiprocessing - does everything except call rosetta
def dummy_funct(resfile):
    # time this job
    time1 = time.time()

    # generate rosetta command line args
    # required flags
    rosetta_cmd = [
    os.path.join(rosetta_bindir,'%s.default.%s' % (rosetta_appname, platform_tag)),
    '-in:file:s',input_pdb_file,
    '-resfile',resfile,
    '-in:file:fullatom',
    '-ignore_unrecognized_res',
    '-fa_max_dis','9.0',
    '-ddg::suppress_checkpointing','true',
    '-ddg:weight_file','soft_rep_design',
    '-ddg::iterations',str(iterations),
    '-ddg::local_opt_only','false',
    '-ddg::min_cst','true',
    '-constraints::cst_file',cst_filename,
    '-ddg::sc_min_only','false',
    '-ddg::ramp_repulsive','true',
    '-ddg::suppress_checkpointing', 'true',
    '-in:auto_setup_metals'
    ]
    # conditional flags
    # add paramsfile option if needed !!UNTESTED!!
    if input_params_file:
        rosetta_cmd.append('-extra_res_fa')
        rosetta_cmd.append(input_params_file)
    # write out pdbs?
    if write_pdbs:
        rosetta_cmd.append('-ddg::dump_pdbs')
        rosetta_cmd.append('true')
    else:
        rosetta_cmd.append('-ddg::dump_pdbs')
        rosetta_cmd.append('false')
    # report mean ddg score?
    if report_mean:
        rosetta_cmd.append('-ddg::mean')
        rosetta_cmd.append('true')
    else:
        rosetta_cmd.append('-ddg::mean')
        rosetta_cmd.append('false')
    # report min ddg score?
    if report_min:
        rosetta_cmd.append('-ddg::min')
        rosetta_cmd.append('true')
    else:
        rosetta_cmd.append('-ddg::min')
        rosetta_cmd.append('false')

    # make a directory for this mutation
    mutation_name = resfile.split('/')[-1].split('.')[0]
    job_dir = os.path.join(output_dir, mutation_name)
    os.makedirs(job_dir)

    # write some system info to the log
    os.chdir(job_dir)
    with open('ddg%s.log' % mutation_name, 'w') as logfile:
        logfile.write("Python: %s\n" % sys.version)
        logfile.write("Host: %s\n" % socket.gethostname())
        logfile.write(' '.join(rosetta_cmd))
        logfile.write('\n')

    # # call rosetta and output to log
    # with open('ddg%s.log' % mutation_name, 'a+') as logfile:
    #     process = subprocess.Popen(rosetta_cmd, \
    #                                stdout=logfile, \
    #                                stderr=subprocess.STDOUT, \
    #                                close_fds = True)
    #     returncode = process.wait()

    fake_cmd = ['echo', '\'%s\'' % mutation_name]
    process = subprocess.Popen(fake_cmd, close_fds=True)
    returncode = process.wait()

    time.sleep(5)

    # write timing info to log
    time2 = time.time()
    runtime = time2 - time1
    with open('ddg%s.log' % mutation_name, 'a+') as logfile:
        logfile.write('\nruntime in sec: %s ' % str(runtime))

p = multiprocessing.Pool(processes)
#p.map(dummy_funct, resfiles)
p.map(run_ddg_monomer, resfiles)
